using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class View_V_Control_LookData : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

    }

    protected void Button1_Click(object sender, EventArgs e)
    {
        GridView1.AutoGenerateDeleteButton = !GridView1.AutoGenerateDeleteButton;
        GridView1.AutoGenerateEditButton = !GridView1.AutoGenerateEditButton;
    }
}